// flow-typed signature: 01e80020b3c0cd71030be7da94e23567
// flow-typed version: <<STUB>>/two.js_v^0.7.0-alpha.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'two.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'two.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'two.js/build/two' {
  declare module.exports: any;
}

declare module 'two.js/build/two.min' {
  declare module.exports: any;
}

declare module 'two.js/src/anchor' {
  declare module.exports: any;
}

declare module 'two.js/src/effects/gradient' {
  declare module.exports: any;
}

declare module 'two.js/src/effects/image-sequence' {
  declare module.exports: any;
}

declare module 'two.js/src/effects/linear-gradient' {
  declare module.exports: any;
}

declare module 'two.js/src/effects/radial-gradient' {
  declare module.exports: any;
}

declare module 'two.js/src/effects/sprite' {
  declare module.exports: any;
}

declare module 'two.js/src/effects/texture' {
  declare module.exports: any;
}

declare module 'two.js/src/group' {
  declare module.exports: any;
}

declare module 'two.js/src/matrix' {
  declare module.exports: any;
}

declare module 'two.js/src/path' {
  declare module.exports: any;
}

declare module 'two.js/src/registry' {
  declare module.exports: any;
}

declare module 'two.js/src/renderer/canvas' {
  declare module.exports: any;
}

declare module 'two.js/src/renderer/svg' {
  declare module.exports: any;
}

declare module 'two.js/src/renderer/webgl' {
  declare module.exports: any;
}

declare module 'two.js/src/shape' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/arc-segment' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/circle' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/ellipse' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/line' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/polygon' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/rectangle' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/rounded-rectangle' {
  declare module.exports: any;
}

declare module 'two.js/src/shapes/star' {
  declare module.exports: any;
}

declare module 'two.js/src/text' {
  declare module.exports: any;
}

declare module 'two.js/src/two' {
  declare module.exports: any;
}

declare module 'two.js/src/vector' {
  declare module.exports: any;
}

declare module 'two.js/tests/src/utils' {
  declare module.exports: any;
}

declare module 'two.js/tests/suite/bounding-box' {
  declare module.exports: any;
}

declare module 'two.js/tests/suite/canvas' {
  declare module.exports: any;
}

declare module 'two.js/tests/suite/core' {
  declare module.exports: any;
}

declare module 'two.js/tests/suite/svg-interpreter' {
  declare module.exports: any;
}

declare module 'two.js/tests/suite/svg' {
  declare module.exports: any;
}

declare module 'two.js/tests/suite/webgl' {
  declare module.exports: any;
}

declare module 'two.js/two.extern' {
  declare module.exports: any;
}

declare module 'two.js/utils/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'two.js/build/two.js' {
  declare module.exports: $Exports<'two.js/build/two'>;
}
declare module 'two.js/build/two.min.js' {
  declare module.exports: $Exports<'two.js/build/two.min'>;
}
declare module 'two.js/src/anchor.js' {
  declare module.exports: $Exports<'two.js/src/anchor'>;
}
declare module 'two.js/src/effects/gradient.js' {
  declare module.exports: $Exports<'two.js/src/effects/gradient'>;
}
declare module 'two.js/src/effects/image-sequence.js' {
  declare module.exports: $Exports<'two.js/src/effects/image-sequence'>;
}
declare module 'two.js/src/effects/linear-gradient.js' {
  declare module.exports: $Exports<'two.js/src/effects/linear-gradient'>;
}
declare module 'two.js/src/effects/radial-gradient.js' {
  declare module.exports: $Exports<'two.js/src/effects/radial-gradient'>;
}
declare module 'two.js/src/effects/sprite.js' {
  declare module.exports: $Exports<'two.js/src/effects/sprite'>;
}
declare module 'two.js/src/effects/texture.js' {
  declare module.exports: $Exports<'two.js/src/effects/texture'>;
}
declare module 'two.js/src/group.js' {
  declare module.exports: $Exports<'two.js/src/group'>;
}
declare module 'two.js/src/matrix.js' {
  declare module.exports: $Exports<'two.js/src/matrix'>;
}
declare module 'two.js/src/path.js' {
  declare module.exports: $Exports<'two.js/src/path'>;
}
declare module 'two.js/src/registry.js' {
  declare module.exports: $Exports<'two.js/src/registry'>;
}
declare module 'two.js/src/renderer/canvas.js' {
  declare module.exports: $Exports<'two.js/src/renderer/canvas'>;
}
declare module 'two.js/src/renderer/svg.js' {
  declare module.exports: $Exports<'two.js/src/renderer/svg'>;
}
declare module 'two.js/src/renderer/webgl.js' {
  declare module.exports: $Exports<'two.js/src/renderer/webgl'>;
}
declare module 'two.js/src/shape.js' {
  declare module.exports: $Exports<'two.js/src/shape'>;
}
declare module 'two.js/src/shapes/arc-segment.js' {
  declare module.exports: $Exports<'two.js/src/shapes/arc-segment'>;
}
declare module 'two.js/src/shapes/circle.js' {
  declare module.exports: $Exports<'two.js/src/shapes/circle'>;
}
declare module 'two.js/src/shapes/ellipse.js' {
  declare module.exports: $Exports<'two.js/src/shapes/ellipse'>;
}
declare module 'two.js/src/shapes/line.js' {
  declare module.exports: $Exports<'two.js/src/shapes/line'>;
}
declare module 'two.js/src/shapes/polygon.js' {
  declare module.exports: $Exports<'two.js/src/shapes/polygon'>;
}
declare module 'two.js/src/shapes/rectangle.js' {
  declare module.exports: $Exports<'two.js/src/shapes/rectangle'>;
}
declare module 'two.js/src/shapes/rounded-rectangle.js' {
  declare module.exports: $Exports<'two.js/src/shapes/rounded-rectangle'>;
}
declare module 'two.js/src/shapes/star.js' {
  declare module.exports: $Exports<'two.js/src/shapes/star'>;
}
declare module 'two.js/src/text.js' {
  declare module.exports: $Exports<'two.js/src/text'>;
}
declare module 'two.js/src/two.js' {
  declare module.exports: $Exports<'two.js/src/two'>;
}
declare module 'two.js/src/vector.js' {
  declare module.exports: $Exports<'two.js/src/vector'>;
}
declare module 'two.js/tests/src/utils.js' {
  declare module.exports: $Exports<'two.js/tests/src/utils'>;
}
declare module 'two.js/tests/suite/bounding-box.js' {
  declare module.exports: $Exports<'two.js/tests/suite/bounding-box'>;
}
declare module 'two.js/tests/suite/canvas.js' {
  declare module.exports: $Exports<'two.js/tests/suite/canvas'>;
}
declare module 'two.js/tests/suite/core.js' {
  declare module.exports: $Exports<'two.js/tests/suite/core'>;
}
declare module 'two.js/tests/suite/svg-interpreter.js' {
  declare module.exports: $Exports<'two.js/tests/suite/svg-interpreter'>;
}
declare module 'two.js/tests/suite/svg.js' {
  declare module.exports: $Exports<'two.js/tests/suite/svg'>;
}
declare module 'two.js/tests/suite/webgl.js' {
  declare module.exports: $Exports<'two.js/tests/suite/webgl'>;
}
declare module 'two.js/two.extern.js' {
  declare module.exports: $Exports<'two.js/two.extern'>;
}
declare module 'two.js/utils/build.js' {
  declare module.exports: $Exports<'two.js/utils/build'>;
}
