// flow-typed signature: 3a11c6a40ecd3594d83d6fa3ad66c5c6
// flow-typed version: <<STUB>>/v-bar_v^3.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'v-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'v-bar' {
  declare module.exports: any;
}
