// flow-typed signature: 144c64de5658b14bbfa833734ca6aa4c
// flow-typed version: <<STUB>>/vue-draggable-resizable_v^1.5.4/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-draggable-resizable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-draggable-resizable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-draggable-resizable/build/dev-client' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/build/dev-server' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/build/webpack.base' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/build/webpack.dev' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/build/webpack.dist' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/build/webpack.docs' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/build/webpack.test' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/config/index' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/dist/index' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/docs/app' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/docs/resources/app.min' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/src/index' {
  declare module.exports: any;
}

declare module 'vue-draggable-resizable/src/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-draggable-resizable/build/dev-client.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/dev-client'>;
}
declare module 'vue-draggable-resizable/build/dev-server.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/dev-server'>;
}
declare module 'vue-draggable-resizable/build/webpack.base.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/webpack.base'>;
}
declare module 'vue-draggable-resizable/build/webpack.dev.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/webpack.dev'>;
}
declare module 'vue-draggable-resizable/build/webpack.dist.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/webpack.dist'>;
}
declare module 'vue-draggable-resizable/build/webpack.docs.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/webpack.docs'>;
}
declare module 'vue-draggable-resizable/build/webpack.test.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/build/webpack.test'>;
}
declare module 'vue-draggable-resizable/config/index.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/config/index'>;
}
declare module 'vue-draggable-resizable/dist/index.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/dist/index'>;
}
declare module 'vue-draggable-resizable/docs/app.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/docs/app'>;
}
declare module 'vue-draggable-resizable/docs/resources/app.min.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/docs/resources/app.min'>;
}
declare module 'vue-draggable-resizable/src/index.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/src/index'>;
}
declare module 'vue-draggable-resizable/src/main.js' {
  declare module.exports: $Exports<'vue-draggable-resizable/src/main'>;
}
