// flow-typed signature: e64f9b93a627a1ccc1039ae5e8b172fb
// flow-typed version: <<STUB>>/vue2-animate_v^1.0.4/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue2-animate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue2-animate' {
  declare module.exports: any;
}
