// flow-typed signature: 39cef25cb3245b2c16c5264b8199e2da
// flow-typed version: <<STUB>>/vuebar_v^0.0.17/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuebar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuebar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuebar/vuebar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuebar/vuebar.js' {
  declare module.exports: $Exports<'vuebar/vuebar'>;
}
