// flow-typed signature: 7da730c7c235d603817166b898c0f222
// flow-typed version: <<STUB>>/vuetify_v^1.0.6/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuetify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuetify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuetify/dist/vuetify' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify.min' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/transitions/expand-transition' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/transitions/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VAlert/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VAlert/VAlert' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VApp/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VApp/mixins/app-breakpoint' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VApp/mixins/app-theme' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VApp/VApp' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VAvatar/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VAvatar/VAvatar' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBadge/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBadge/VBadge' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBottomNav/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBottomNav/VBottomNav' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBottomSheet/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBottomSheet/VBottomSheet' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBreadcrumbs/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBreadcrumbs/VBreadcrumbs' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBreadcrumbs/VBreadcrumbsItem' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBtn/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBtn/VBtn' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBtnToggle/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VBtnToggle/VBtnToggle' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCard/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCard/VCard' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCard/VCardMedia' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCard/VCardTitle' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCarousel/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCarousel/VCarousel' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCarousel/VCarouselItem' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCheckbox/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VCheckbox/VCheckbox' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VChip/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VChip/VChip' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataIterator/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataIterator/VDataIterator' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/mixins/body' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/mixins/foot' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/mixins/head' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/mixins/progress' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/VDataTable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDataTable/VEditDialog' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/mixins/date-picker-table' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/util/createNativeLocaleFormatter' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/util/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/util/isDateAllowed' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/util/monthChange' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/util/pad' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/VDatePicker' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/VDatePickerDateTable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/VDatePickerHeader' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/VDatePickerMonthTable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/VDatePickerTitle' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDatePicker/VDatePickerYears' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDialog/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDialog/VDialog' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDivider/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VDivider/VDivider' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VExpansionPanel/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VExpansionPanel/VExpansionPanel' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VExpansionPanel/VExpansionPanelContent' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VFooter/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VFooter/VFooter' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VForm/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VForm/VForm' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VGrid/grid' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VGrid/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VGrid/VContainer' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VGrid/VContent' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VGrid/VFlex' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VGrid/VLayout' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VIcon/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VIcon/VIcon' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VJumbotron/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VJumbotron/VJumbotron' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VList/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VList/VList' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VList/VListGroup' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VList/VListTile' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VList/VListTileAction' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VList/VListTileAvatar' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VMenu/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VMenu/mixins/menu-activator' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VMenu/mixins/menu-generators' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VMenu/mixins/menu-keyable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VMenu/mixins/menu-position' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VMenu/VMenu' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VNavigationDrawer/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VNavigationDrawer/VNavigationDrawer' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VPagination/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VPagination/VPagination' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VParallax/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VParallax/VParallax' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VPicker/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VPicker/VPicker' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VProgressCircular/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VProgressCircular/VProgressCircular' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VProgressLinear/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VProgressLinear/VProgressLinear' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VRadioGroup/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VRadioGroup/VRadio' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VRadioGroup/VRadioGroup' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-autocomplete' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-computed' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-events' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-generators' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-helpers' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-menu' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-props' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/mixins/select-watchers' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSelect/VSelect' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSlider/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSlider/VSlider' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSnackbar/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSnackbar/VSnackbar' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSpeedDial/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSpeedDial/VSpeedDial' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VStepper/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VStepper/VStepper' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VStepper/VStepperContent' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VStepper/VStepperStep' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSubheader/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSubheader/VSubheader' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSwitch/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSwitch/VSwitch' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSystemBar/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VSystemBar/VSystemBar' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/mixins/tabs-computed' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/mixins/tabs-generators' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/mixins/tabs-props' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/mixins/tabs-touch' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/mixins/tabs-watchers' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/VTab' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/VTabItem' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/VTabs' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/VTabsItems' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTabs/VTabsSlider' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTextField/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTextField/VTextField' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTimePicker/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTimePicker/VTimePicker' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTimePicker/VTimePickerClock' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTimePicker/VTimePickerTitle' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VToolbar/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VToolbar/VToolbar' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VToolbar/VToolbarSideIcon' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTooltip/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/VTooltip/VTooltip' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/Vuetify/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/Vuetify/mixins/application' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/Vuetify/mixins/options' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/Vuetify/mixins/theme' {
  declare module.exports: any;
}

declare module 'vuetify/es5/components/Vuetify/util/goTo' {
  declare module.exports: any;
}

declare module 'vuetify/es5/directives/click-outside' {
  declare module.exports: any;
}

declare module 'vuetify/es5/directives/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/directives/resize' {
  declare module.exports: any;
}

declare module 'vuetify/es5/directives/ripple' {
  declare module.exports: any;
}

declare module 'vuetify/es5/directives/scroll' {
  declare module.exports: any;
}

declare module 'vuetify/es5/directives/touch' {
  declare module.exports: any;
}

declare module 'vuetify/es5/index' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/applicationable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/bootable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/button-group' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/colorable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/data-iterable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/delayable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/dependent' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/detachable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/filterable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/input' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/loadable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/maskable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/menuable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/overlayable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/picker-button' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/picker' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/positionable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/registrable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/returnable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/rippleable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/routable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/selectable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/soloable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/ssr-bootable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/stackable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/tab-focusable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/themeable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/toggleable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/transitionable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/translatable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/mixins/validatable' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/color/transformCIELAB' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/color/transformSRGB' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/colors' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/colorUtils' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/console' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/easing-patterns' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/helpers' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/mask' {
  declare module.exports: any;
}

declare module 'vuetify/es5/util/theme' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/transitions/expand-transition' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/transitions/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VAlert/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VAlert/VAlert' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VApp/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VApp/mixins/app-breakpoint' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VApp/mixins/app-theme' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VApp/VApp' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VAvatar/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VAvatar/VAvatar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBadge/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBadge/VBadge' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBottomNav/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBottomNav/VBottomNav' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBottomSheet/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBottomSheet/VBottomSheet' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBreadcrumbs/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBreadcrumbs/VBreadcrumbs' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBreadcrumbs/VBreadcrumbsItem' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBtn/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBtn/VBtn' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBtnToggle/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VBtnToggle/VBtnToggle' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCard/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCard/VCard' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCard/VCardMedia' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCard/VCardTitle' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCarousel/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCarousel/VCarousel' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCarousel/VCarouselItem' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCheckbox/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VCheckbox/VCheckbox' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VChip/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VChip/VChip' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataIterator/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataIterator/VDataIterator' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/mixins/body' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/mixins/foot' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/mixins/head' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/mixins/progress' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/VDataTable' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDataTable/VEditDialog' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/mixins/date-picker-table' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/util/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/util/isDateAllowed' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/util/monthChange' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/util/pad' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/VDatePicker' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/VDatePickerDateTable' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/VDatePickerHeader' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/VDatePickerMonthTable' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/VDatePickerTitle' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDatePicker/VDatePickerYears' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDialog/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDialog/VDialog' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDivider/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VDivider/VDivider' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VExpansionPanel/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VExpansionPanel/VExpansionPanel' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VExpansionPanel/VExpansionPanelContent' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VFooter/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VFooter/VFooter' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VForm/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VForm/VForm' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VGrid/grid' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VGrid/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VGrid/VContainer' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VGrid/VContent' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VGrid/VFlex' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VGrid/VLayout' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VIcon/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VIcon/VIcon' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VJumbotron/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VJumbotron/VJumbotron' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VList/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VList/VList' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VList/VListGroup' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VList/VListTile' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VList/VListTileAction' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VList/VListTileAvatar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VMenu/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VMenu/mixins/menu-activator' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VMenu/mixins/menu-generators' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VMenu/mixins/menu-keyable' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VMenu/mixins/menu-position' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VMenu/VMenu' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VNavigationDrawer/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VNavigationDrawer/VNavigationDrawer' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VPagination/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VPagination/VPagination' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VParallax/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VParallax/VParallax' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VPicker/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VPicker/VPicker' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VProgressCircular/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VProgressCircular/VProgressCircular' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VProgressLinear/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VProgressLinear/VProgressLinear' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VRadioGroup/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VRadioGroup/VRadio' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VRadioGroup/VRadioGroup' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-autocomplete' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-computed' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-events' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-generators' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-helpers' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-menu' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-props' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/mixins/select-watchers' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSelect/VSelect' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSlider/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSlider/VSlider' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSnackbar/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSnackbar/VSnackbar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSpeedDial/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSpeedDial/VSpeedDial' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VStepper/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VStepper/VStepper' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VStepper/VStepperContent' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VStepper/VStepperStep' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSubheader/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSubheader/VSubheader' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSwitch/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSwitch/VSwitch' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSystemBar/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VSystemBar/VSystemBar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/mixins/tabs-computed' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/mixins/tabs-generators' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/mixins/tabs-props' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/mixins/tabs-touch' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/mixins/tabs-watchers' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/VTab' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/VTabItem' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/VTabs' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/VTabsItems' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTabs/VTabsSlider' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTextField/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTextField/VTextField' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTimePicker/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTimePicker/VTimePicker' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTimePicker/VTimePickerClock' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTimePicker/VTimePickerTitle' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VToolbar/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VToolbar/VToolbar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VToolbar/VToolbarSideIcon' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTooltip/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/VTooltip/VTooltip' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/Vuetify/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/Vuetify/mixins/application' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/Vuetify/mixins/options' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/Vuetify/mixins/theme' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/Vuetify/util/goTo' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/click-outside' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/resize' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/ripple' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/scroll' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/touch' {
  declare module.exports: any;
}

declare module 'vuetify/src/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/applicationable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/bootable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/button-group' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/colorable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/data-iterable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/delayable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/dependent' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/detachable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/filterable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/input' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/loadable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/maskable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/menuable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/overlayable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/picker-button' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/picker' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/positionable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/registrable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/returnable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/rippleable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/routable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/selectable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/soloable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/ssr-bootable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/stackable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/tab-focusable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/themeable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/toggleable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/transitionable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/translatable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/validatable' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/color/transformCIELAB' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/color/transformSRGB' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/colors' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/colorUtils' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/console' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/easing-patterns' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/helpers' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/mask' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/theme' {
  declare module.exports: any;
}

declare module 'vuetify/test/index' {
  declare module.exports: any;
}

declare module 'vuetify/test/util/to-have-been-warned' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuetify/dist/vuetify.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify'>;
}
declare module 'vuetify/dist/vuetify.min.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify.min'>;
}
declare module 'vuetify/es5/components/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/index'>;
}
declare module 'vuetify/es5/components/transitions/expand-transition.js' {
  declare module.exports: $Exports<'vuetify/es5/components/transitions/expand-transition'>;
}
declare module 'vuetify/es5/components/transitions/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/transitions/index'>;
}
declare module 'vuetify/es5/components/VAlert/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VAlert/index'>;
}
declare module 'vuetify/es5/components/VAlert/VAlert.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VAlert/VAlert'>;
}
declare module 'vuetify/es5/components/VApp/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VApp/index'>;
}
declare module 'vuetify/es5/components/VApp/mixins/app-breakpoint.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VApp/mixins/app-breakpoint'>;
}
declare module 'vuetify/es5/components/VApp/mixins/app-theme.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VApp/mixins/app-theme'>;
}
declare module 'vuetify/es5/components/VApp/VApp.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VApp/VApp'>;
}
declare module 'vuetify/es5/components/VAvatar/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VAvatar/index'>;
}
declare module 'vuetify/es5/components/VAvatar/VAvatar.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VAvatar/VAvatar'>;
}
declare module 'vuetify/es5/components/VBadge/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBadge/index'>;
}
declare module 'vuetify/es5/components/VBadge/VBadge.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBadge/VBadge'>;
}
declare module 'vuetify/es5/components/VBottomNav/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBottomNav/index'>;
}
declare module 'vuetify/es5/components/VBottomNav/VBottomNav.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBottomNav/VBottomNav'>;
}
declare module 'vuetify/es5/components/VBottomSheet/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBottomSheet/index'>;
}
declare module 'vuetify/es5/components/VBottomSheet/VBottomSheet.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBottomSheet/VBottomSheet'>;
}
declare module 'vuetify/es5/components/VBreadcrumbs/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBreadcrumbs/index'>;
}
declare module 'vuetify/es5/components/VBreadcrumbs/VBreadcrumbs.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBreadcrumbs/VBreadcrumbs'>;
}
declare module 'vuetify/es5/components/VBreadcrumbs/VBreadcrumbsItem.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBreadcrumbs/VBreadcrumbsItem'>;
}
declare module 'vuetify/es5/components/VBtn/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBtn/index'>;
}
declare module 'vuetify/es5/components/VBtn/VBtn.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBtn/VBtn'>;
}
declare module 'vuetify/es5/components/VBtnToggle/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBtnToggle/index'>;
}
declare module 'vuetify/es5/components/VBtnToggle/VBtnToggle.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VBtnToggle/VBtnToggle'>;
}
declare module 'vuetify/es5/components/VCard/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCard/index'>;
}
declare module 'vuetify/es5/components/VCard/VCard.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCard/VCard'>;
}
declare module 'vuetify/es5/components/VCard/VCardMedia.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCard/VCardMedia'>;
}
declare module 'vuetify/es5/components/VCard/VCardTitle.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCard/VCardTitle'>;
}
declare module 'vuetify/es5/components/VCarousel/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCarousel/index'>;
}
declare module 'vuetify/es5/components/VCarousel/VCarousel.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCarousel/VCarousel'>;
}
declare module 'vuetify/es5/components/VCarousel/VCarouselItem.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCarousel/VCarouselItem'>;
}
declare module 'vuetify/es5/components/VCheckbox/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCheckbox/index'>;
}
declare module 'vuetify/es5/components/VCheckbox/VCheckbox.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VCheckbox/VCheckbox'>;
}
declare module 'vuetify/es5/components/VChip/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VChip/index'>;
}
declare module 'vuetify/es5/components/VChip/VChip.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VChip/VChip'>;
}
declare module 'vuetify/es5/components/VDataIterator/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataIterator/index'>;
}
declare module 'vuetify/es5/components/VDataIterator/VDataIterator.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataIterator/VDataIterator'>;
}
declare module 'vuetify/es5/components/VDataTable/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/index'>;
}
declare module 'vuetify/es5/components/VDataTable/mixins/body.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/mixins/body'>;
}
declare module 'vuetify/es5/components/VDataTable/mixins/foot.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/mixins/foot'>;
}
declare module 'vuetify/es5/components/VDataTable/mixins/head.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/mixins/head'>;
}
declare module 'vuetify/es5/components/VDataTable/mixins/progress.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/mixins/progress'>;
}
declare module 'vuetify/es5/components/VDataTable/VDataTable.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/VDataTable'>;
}
declare module 'vuetify/es5/components/VDataTable/VEditDialog.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDataTable/VEditDialog'>;
}
declare module 'vuetify/es5/components/VDatePicker/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/index'>;
}
declare module 'vuetify/es5/components/VDatePicker/mixins/date-picker-table.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/mixins/date-picker-table'>;
}
declare module 'vuetify/es5/components/VDatePicker/util/createNativeLocaleFormatter.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/util/createNativeLocaleFormatter'>;
}
declare module 'vuetify/es5/components/VDatePicker/util/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/util/index'>;
}
declare module 'vuetify/es5/components/VDatePicker/util/isDateAllowed.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/util/isDateAllowed'>;
}
declare module 'vuetify/es5/components/VDatePicker/util/monthChange.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/util/monthChange'>;
}
declare module 'vuetify/es5/components/VDatePicker/util/pad.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/util/pad'>;
}
declare module 'vuetify/es5/components/VDatePicker/VDatePicker.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/VDatePicker'>;
}
declare module 'vuetify/es5/components/VDatePicker/VDatePickerDateTable.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/VDatePickerDateTable'>;
}
declare module 'vuetify/es5/components/VDatePicker/VDatePickerHeader.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/VDatePickerHeader'>;
}
declare module 'vuetify/es5/components/VDatePicker/VDatePickerMonthTable.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/VDatePickerMonthTable'>;
}
declare module 'vuetify/es5/components/VDatePicker/VDatePickerTitle.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/VDatePickerTitle'>;
}
declare module 'vuetify/es5/components/VDatePicker/VDatePickerYears.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDatePicker/VDatePickerYears'>;
}
declare module 'vuetify/es5/components/VDialog/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDialog/index'>;
}
declare module 'vuetify/es5/components/VDialog/VDialog.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDialog/VDialog'>;
}
declare module 'vuetify/es5/components/VDivider/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDivider/index'>;
}
declare module 'vuetify/es5/components/VDivider/VDivider.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VDivider/VDivider'>;
}
declare module 'vuetify/es5/components/VExpansionPanel/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VExpansionPanel/index'>;
}
declare module 'vuetify/es5/components/VExpansionPanel/VExpansionPanel.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VExpansionPanel/VExpansionPanel'>;
}
declare module 'vuetify/es5/components/VExpansionPanel/VExpansionPanelContent.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VExpansionPanel/VExpansionPanelContent'>;
}
declare module 'vuetify/es5/components/VFooter/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VFooter/index'>;
}
declare module 'vuetify/es5/components/VFooter/VFooter.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VFooter/VFooter'>;
}
declare module 'vuetify/es5/components/VForm/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VForm/index'>;
}
declare module 'vuetify/es5/components/VForm/VForm.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VForm/VForm'>;
}
declare module 'vuetify/es5/components/VGrid/grid.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VGrid/grid'>;
}
declare module 'vuetify/es5/components/VGrid/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VGrid/index'>;
}
declare module 'vuetify/es5/components/VGrid/VContainer.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VGrid/VContainer'>;
}
declare module 'vuetify/es5/components/VGrid/VContent.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VGrid/VContent'>;
}
declare module 'vuetify/es5/components/VGrid/VFlex.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VGrid/VFlex'>;
}
declare module 'vuetify/es5/components/VGrid/VLayout.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VGrid/VLayout'>;
}
declare module 'vuetify/es5/components/VIcon/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VIcon/index'>;
}
declare module 'vuetify/es5/components/VIcon/VIcon.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VIcon/VIcon'>;
}
declare module 'vuetify/es5/components/VJumbotron/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VJumbotron/index'>;
}
declare module 'vuetify/es5/components/VJumbotron/VJumbotron.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VJumbotron/VJumbotron'>;
}
declare module 'vuetify/es5/components/VList/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VList/index'>;
}
declare module 'vuetify/es5/components/VList/VList.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VList/VList'>;
}
declare module 'vuetify/es5/components/VList/VListGroup.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VList/VListGroup'>;
}
declare module 'vuetify/es5/components/VList/VListTile.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VList/VListTile'>;
}
declare module 'vuetify/es5/components/VList/VListTileAction.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VList/VListTileAction'>;
}
declare module 'vuetify/es5/components/VList/VListTileAvatar.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VList/VListTileAvatar'>;
}
declare module 'vuetify/es5/components/VMenu/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VMenu/index'>;
}
declare module 'vuetify/es5/components/VMenu/mixins/menu-activator.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VMenu/mixins/menu-activator'>;
}
declare module 'vuetify/es5/components/VMenu/mixins/menu-generators.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VMenu/mixins/menu-generators'>;
}
declare module 'vuetify/es5/components/VMenu/mixins/menu-keyable.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VMenu/mixins/menu-keyable'>;
}
declare module 'vuetify/es5/components/VMenu/mixins/menu-position.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VMenu/mixins/menu-position'>;
}
declare module 'vuetify/es5/components/VMenu/VMenu.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VMenu/VMenu'>;
}
declare module 'vuetify/es5/components/VNavigationDrawer/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VNavigationDrawer/index'>;
}
declare module 'vuetify/es5/components/VNavigationDrawer/VNavigationDrawer.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VNavigationDrawer/VNavigationDrawer'>;
}
declare module 'vuetify/es5/components/VPagination/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VPagination/index'>;
}
declare module 'vuetify/es5/components/VPagination/VPagination.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VPagination/VPagination'>;
}
declare module 'vuetify/es5/components/VParallax/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VParallax/index'>;
}
declare module 'vuetify/es5/components/VParallax/VParallax.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VParallax/VParallax'>;
}
declare module 'vuetify/es5/components/VPicker/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VPicker/index'>;
}
declare module 'vuetify/es5/components/VPicker/VPicker.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VPicker/VPicker'>;
}
declare module 'vuetify/es5/components/VProgressCircular/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VProgressCircular/index'>;
}
declare module 'vuetify/es5/components/VProgressCircular/VProgressCircular.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VProgressCircular/VProgressCircular'>;
}
declare module 'vuetify/es5/components/VProgressLinear/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VProgressLinear/index'>;
}
declare module 'vuetify/es5/components/VProgressLinear/VProgressLinear.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VProgressLinear/VProgressLinear'>;
}
declare module 'vuetify/es5/components/VRadioGroup/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VRadioGroup/index'>;
}
declare module 'vuetify/es5/components/VRadioGroup/VRadio.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VRadioGroup/VRadio'>;
}
declare module 'vuetify/es5/components/VRadioGroup/VRadioGroup.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VRadioGroup/VRadioGroup'>;
}
declare module 'vuetify/es5/components/VSelect/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/index'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-autocomplete.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-autocomplete'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-computed.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-computed'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-events.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-events'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-generators.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-generators'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-helpers.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-helpers'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-menu.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-menu'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-props.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-props'>;
}
declare module 'vuetify/es5/components/VSelect/mixins/select-watchers.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/mixins/select-watchers'>;
}
declare module 'vuetify/es5/components/VSelect/VSelect.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSelect/VSelect'>;
}
declare module 'vuetify/es5/components/VSlider/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSlider/index'>;
}
declare module 'vuetify/es5/components/VSlider/VSlider.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSlider/VSlider'>;
}
declare module 'vuetify/es5/components/VSnackbar/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSnackbar/index'>;
}
declare module 'vuetify/es5/components/VSnackbar/VSnackbar.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSnackbar/VSnackbar'>;
}
declare module 'vuetify/es5/components/VSpeedDial/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSpeedDial/index'>;
}
declare module 'vuetify/es5/components/VSpeedDial/VSpeedDial.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSpeedDial/VSpeedDial'>;
}
declare module 'vuetify/es5/components/VStepper/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VStepper/index'>;
}
declare module 'vuetify/es5/components/VStepper/VStepper.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VStepper/VStepper'>;
}
declare module 'vuetify/es5/components/VStepper/VStepperContent.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VStepper/VStepperContent'>;
}
declare module 'vuetify/es5/components/VStepper/VStepperStep.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VStepper/VStepperStep'>;
}
declare module 'vuetify/es5/components/VSubheader/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSubheader/index'>;
}
declare module 'vuetify/es5/components/VSubheader/VSubheader.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSubheader/VSubheader'>;
}
declare module 'vuetify/es5/components/VSwitch/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSwitch/index'>;
}
declare module 'vuetify/es5/components/VSwitch/VSwitch.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSwitch/VSwitch'>;
}
declare module 'vuetify/es5/components/VSystemBar/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSystemBar/index'>;
}
declare module 'vuetify/es5/components/VSystemBar/VSystemBar.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VSystemBar/VSystemBar'>;
}
declare module 'vuetify/es5/components/VTabs/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/index'>;
}
declare module 'vuetify/es5/components/VTabs/mixins/tabs-computed.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/mixins/tabs-computed'>;
}
declare module 'vuetify/es5/components/VTabs/mixins/tabs-generators.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/mixins/tabs-generators'>;
}
declare module 'vuetify/es5/components/VTabs/mixins/tabs-props.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/mixins/tabs-props'>;
}
declare module 'vuetify/es5/components/VTabs/mixins/tabs-touch.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/mixins/tabs-touch'>;
}
declare module 'vuetify/es5/components/VTabs/mixins/tabs-watchers.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/mixins/tabs-watchers'>;
}
declare module 'vuetify/es5/components/VTabs/VTab.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/VTab'>;
}
declare module 'vuetify/es5/components/VTabs/VTabItem.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/VTabItem'>;
}
declare module 'vuetify/es5/components/VTabs/VTabs.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/VTabs'>;
}
declare module 'vuetify/es5/components/VTabs/VTabsItems.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/VTabsItems'>;
}
declare module 'vuetify/es5/components/VTabs/VTabsSlider.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTabs/VTabsSlider'>;
}
declare module 'vuetify/es5/components/VTextField/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTextField/index'>;
}
declare module 'vuetify/es5/components/VTextField/VTextField.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTextField/VTextField'>;
}
declare module 'vuetify/es5/components/VTimePicker/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTimePicker/index'>;
}
declare module 'vuetify/es5/components/VTimePicker/VTimePicker.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTimePicker/VTimePicker'>;
}
declare module 'vuetify/es5/components/VTimePicker/VTimePickerClock.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTimePicker/VTimePickerClock'>;
}
declare module 'vuetify/es5/components/VTimePicker/VTimePickerTitle.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTimePicker/VTimePickerTitle'>;
}
declare module 'vuetify/es5/components/VToolbar/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VToolbar/index'>;
}
declare module 'vuetify/es5/components/VToolbar/VToolbar.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VToolbar/VToolbar'>;
}
declare module 'vuetify/es5/components/VToolbar/VToolbarSideIcon.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VToolbar/VToolbarSideIcon'>;
}
declare module 'vuetify/es5/components/VTooltip/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTooltip/index'>;
}
declare module 'vuetify/es5/components/VTooltip/VTooltip.js' {
  declare module.exports: $Exports<'vuetify/es5/components/VTooltip/VTooltip'>;
}
declare module 'vuetify/es5/components/Vuetify/index.js' {
  declare module.exports: $Exports<'vuetify/es5/components/Vuetify/index'>;
}
declare module 'vuetify/es5/components/Vuetify/mixins/application.js' {
  declare module.exports: $Exports<'vuetify/es5/components/Vuetify/mixins/application'>;
}
declare module 'vuetify/es5/components/Vuetify/mixins/options.js' {
  declare module.exports: $Exports<'vuetify/es5/components/Vuetify/mixins/options'>;
}
declare module 'vuetify/es5/components/Vuetify/mixins/theme.js' {
  declare module.exports: $Exports<'vuetify/es5/components/Vuetify/mixins/theme'>;
}
declare module 'vuetify/es5/components/Vuetify/util/goTo.js' {
  declare module.exports: $Exports<'vuetify/es5/components/Vuetify/util/goTo'>;
}
declare module 'vuetify/es5/directives/click-outside.js' {
  declare module.exports: $Exports<'vuetify/es5/directives/click-outside'>;
}
declare module 'vuetify/es5/directives/index.js' {
  declare module.exports: $Exports<'vuetify/es5/directives/index'>;
}
declare module 'vuetify/es5/directives/resize.js' {
  declare module.exports: $Exports<'vuetify/es5/directives/resize'>;
}
declare module 'vuetify/es5/directives/ripple.js' {
  declare module.exports: $Exports<'vuetify/es5/directives/ripple'>;
}
declare module 'vuetify/es5/directives/scroll.js' {
  declare module.exports: $Exports<'vuetify/es5/directives/scroll'>;
}
declare module 'vuetify/es5/directives/touch.js' {
  declare module.exports: $Exports<'vuetify/es5/directives/touch'>;
}
declare module 'vuetify/es5/index.js' {
  declare module.exports: $Exports<'vuetify/es5/index'>;
}
declare module 'vuetify/es5/mixins/applicationable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/applicationable'>;
}
declare module 'vuetify/es5/mixins/bootable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/bootable'>;
}
declare module 'vuetify/es5/mixins/button-group.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/button-group'>;
}
declare module 'vuetify/es5/mixins/colorable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/colorable'>;
}
declare module 'vuetify/es5/mixins/data-iterable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/data-iterable'>;
}
declare module 'vuetify/es5/mixins/delayable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/delayable'>;
}
declare module 'vuetify/es5/mixins/dependent.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/dependent'>;
}
declare module 'vuetify/es5/mixins/detachable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/detachable'>;
}
declare module 'vuetify/es5/mixins/filterable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/filterable'>;
}
declare module 'vuetify/es5/mixins/input.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/input'>;
}
declare module 'vuetify/es5/mixins/loadable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/loadable'>;
}
declare module 'vuetify/es5/mixins/maskable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/maskable'>;
}
declare module 'vuetify/es5/mixins/menuable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/menuable'>;
}
declare module 'vuetify/es5/mixins/overlayable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/overlayable'>;
}
declare module 'vuetify/es5/mixins/picker-button.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/picker-button'>;
}
declare module 'vuetify/es5/mixins/picker.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/picker'>;
}
declare module 'vuetify/es5/mixins/positionable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/positionable'>;
}
declare module 'vuetify/es5/mixins/registrable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/registrable'>;
}
declare module 'vuetify/es5/mixins/returnable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/returnable'>;
}
declare module 'vuetify/es5/mixins/rippleable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/rippleable'>;
}
declare module 'vuetify/es5/mixins/routable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/routable'>;
}
declare module 'vuetify/es5/mixins/selectable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/selectable'>;
}
declare module 'vuetify/es5/mixins/soloable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/soloable'>;
}
declare module 'vuetify/es5/mixins/ssr-bootable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/ssr-bootable'>;
}
declare module 'vuetify/es5/mixins/stackable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/stackable'>;
}
declare module 'vuetify/es5/mixins/tab-focusable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/tab-focusable'>;
}
declare module 'vuetify/es5/mixins/themeable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/themeable'>;
}
declare module 'vuetify/es5/mixins/toggleable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/toggleable'>;
}
declare module 'vuetify/es5/mixins/transitionable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/transitionable'>;
}
declare module 'vuetify/es5/mixins/translatable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/translatable'>;
}
declare module 'vuetify/es5/mixins/validatable.js' {
  declare module.exports: $Exports<'vuetify/es5/mixins/validatable'>;
}
declare module 'vuetify/es5/util/color/transformCIELAB.js' {
  declare module.exports: $Exports<'vuetify/es5/util/color/transformCIELAB'>;
}
declare module 'vuetify/es5/util/color/transformSRGB.js' {
  declare module.exports: $Exports<'vuetify/es5/util/color/transformSRGB'>;
}
declare module 'vuetify/es5/util/colors.js' {
  declare module.exports: $Exports<'vuetify/es5/util/colors'>;
}
declare module 'vuetify/es5/util/colorUtils.js' {
  declare module.exports: $Exports<'vuetify/es5/util/colorUtils'>;
}
declare module 'vuetify/es5/util/console.js' {
  declare module.exports: $Exports<'vuetify/es5/util/console'>;
}
declare module 'vuetify/es5/util/easing-patterns.js' {
  declare module.exports: $Exports<'vuetify/es5/util/easing-patterns'>;
}
declare module 'vuetify/es5/util/helpers.js' {
  declare module.exports: $Exports<'vuetify/es5/util/helpers'>;
}
declare module 'vuetify/es5/util/mask.js' {
  declare module.exports: $Exports<'vuetify/es5/util/mask'>;
}
declare module 'vuetify/es5/util/theme.js' {
  declare module.exports: $Exports<'vuetify/es5/util/theme'>;
}
declare module 'vuetify/src/components/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/index'>;
}
declare module 'vuetify/src/components/transitions/expand-transition.js' {
  declare module.exports: $Exports<'vuetify/src/components/transitions/expand-transition'>;
}
declare module 'vuetify/src/components/transitions/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/transitions/index'>;
}
declare module 'vuetify/src/components/VAlert/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VAlert/index'>;
}
declare module 'vuetify/src/components/VAlert/VAlert.js' {
  declare module.exports: $Exports<'vuetify/src/components/VAlert/VAlert'>;
}
declare module 'vuetify/src/components/VApp/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VApp/index'>;
}
declare module 'vuetify/src/components/VApp/mixins/app-breakpoint.js' {
  declare module.exports: $Exports<'vuetify/src/components/VApp/mixins/app-breakpoint'>;
}
declare module 'vuetify/src/components/VApp/mixins/app-theme.js' {
  declare module.exports: $Exports<'vuetify/src/components/VApp/mixins/app-theme'>;
}
declare module 'vuetify/src/components/VApp/VApp.js' {
  declare module.exports: $Exports<'vuetify/src/components/VApp/VApp'>;
}
declare module 'vuetify/src/components/VAvatar/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VAvatar/index'>;
}
declare module 'vuetify/src/components/VAvatar/VAvatar.js' {
  declare module.exports: $Exports<'vuetify/src/components/VAvatar/VAvatar'>;
}
declare module 'vuetify/src/components/VBadge/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBadge/index'>;
}
declare module 'vuetify/src/components/VBadge/VBadge.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBadge/VBadge'>;
}
declare module 'vuetify/src/components/VBottomNav/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBottomNav/index'>;
}
declare module 'vuetify/src/components/VBottomNav/VBottomNav.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBottomNav/VBottomNav'>;
}
declare module 'vuetify/src/components/VBottomSheet/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBottomSheet/index'>;
}
declare module 'vuetify/src/components/VBottomSheet/VBottomSheet.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBottomSheet/VBottomSheet'>;
}
declare module 'vuetify/src/components/VBreadcrumbs/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBreadcrumbs/index'>;
}
declare module 'vuetify/src/components/VBreadcrumbs/VBreadcrumbs.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBreadcrumbs/VBreadcrumbs'>;
}
declare module 'vuetify/src/components/VBreadcrumbs/VBreadcrumbsItem.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBreadcrumbs/VBreadcrumbsItem'>;
}
declare module 'vuetify/src/components/VBtn/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBtn/index'>;
}
declare module 'vuetify/src/components/VBtn/VBtn.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBtn/VBtn'>;
}
declare module 'vuetify/src/components/VBtnToggle/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBtnToggle/index'>;
}
declare module 'vuetify/src/components/VBtnToggle/VBtnToggle.js' {
  declare module.exports: $Exports<'vuetify/src/components/VBtnToggle/VBtnToggle'>;
}
declare module 'vuetify/src/components/VCard/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCard/index'>;
}
declare module 'vuetify/src/components/VCard/VCard.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCard/VCard'>;
}
declare module 'vuetify/src/components/VCard/VCardMedia.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCard/VCardMedia'>;
}
declare module 'vuetify/src/components/VCard/VCardTitle.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCard/VCardTitle'>;
}
declare module 'vuetify/src/components/VCarousel/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCarousel/index'>;
}
declare module 'vuetify/src/components/VCarousel/VCarousel.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCarousel/VCarousel'>;
}
declare module 'vuetify/src/components/VCarousel/VCarouselItem.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCarousel/VCarouselItem'>;
}
declare module 'vuetify/src/components/VCheckbox/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCheckbox/index'>;
}
declare module 'vuetify/src/components/VCheckbox/VCheckbox.js' {
  declare module.exports: $Exports<'vuetify/src/components/VCheckbox/VCheckbox'>;
}
declare module 'vuetify/src/components/VChip/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VChip/index'>;
}
declare module 'vuetify/src/components/VChip/VChip.js' {
  declare module.exports: $Exports<'vuetify/src/components/VChip/VChip'>;
}
declare module 'vuetify/src/components/VDataIterator/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataIterator/index'>;
}
declare module 'vuetify/src/components/VDataIterator/VDataIterator.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataIterator/VDataIterator'>;
}
declare module 'vuetify/src/components/VDataTable/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/index'>;
}
declare module 'vuetify/src/components/VDataTable/mixins/body.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/mixins/body'>;
}
declare module 'vuetify/src/components/VDataTable/mixins/foot.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/mixins/foot'>;
}
declare module 'vuetify/src/components/VDataTable/mixins/head.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/mixins/head'>;
}
declare module 'vuetify/src/components/VDataTable/mixins/progress.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/mixins/progress'>;
}
declare module 'vuetify/src/components/VDataTable/VDataTable.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/VDataTable'>;
}
declare module 'vuetify/src/components/VDataTable/VEditDialog.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDataTable/VEditDialog'>;
}
declare module 'vuetify/src/components/VDatePicker/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/index'>;
}
declare module 'vuetify/src/components/VDatePicker/mixins/date-picker-table.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/mixins/date-picker-table'>;
}
declare module 'vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/util/createNativeLocaleFormatter'>;
}
declare module 'vuetify/src/components/VDatePicker/util/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/util/index'>;
}
declare module 'vuetify/src/components/VDatePicker/util/isDateAllowed.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/util/isDateAllowed'>;
}
declare module 'vuetify/src/components/VDatePicker/util/monthChange.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/util/monthChange'>;
}
declare module 'vuetify/src/components/VDatePicker/util/pad.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/util/pad'>;
}
declare module 'vuetify/src/components/VDatePicker/VDatePicker.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/VDatePicker'>;
}
declare module 'vuetify/src/components/VDatePicker/VDatePickerDateTable.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/VDatePickerDateTable'>;
}
declare module 'vuetify/src/components/VDatePicker/VDatePickerHeader.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/VDatePickerHeader'>;
}
declare module 'vuetify/src/components/VDatePicker/VDatePickerMonthTable.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/VDatePickerMonthTable'>;
}
declare module 'vuetify/src/components/VDatePicker/VDatePickerTitle.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/VDatePickerTitle'>;
}
declare module 'vuetify/src/components/VDatePicker/VDatePickerYears.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDatePicker/VDatePickerYears'>;
}
declare module 'vuetify/src/components/VDialog/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDialog/index'>;
}
declare module 'vuetify/src/components/VDialog/VDialog.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDialog/VDialog'>;
}
declare module 'vuetify/src/components/VDivider/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDivider/index'>;
}
declare module 'vuetify/src/components/VDivider/VDivider.js' {
  declare module.exports: $Exports<'vuetify/src/components/VDivider/VDivider'>;
}
declare module 'vuetify/src/components/VExpansionPanel/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VExpansionPanel/index'>;
}
declare module 'vuetify/src/components/VExpansionPanel/VExpansionPanel.js' {
  declare module.exports: $Exports<'vuetify/src/components/VExpansionPanel/VExpansionPanel'>;
}
declare module 'vuetify/src/components/VExpansionPanel/VExpansionPanelContent.js' {
  declare module.exports: $Exports<'vuetify/src/components/VExpansionPanel/VExpansionPanelContent'>;
}
declare module 'vuetify/src/components/VFooter/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VFooter/index'>;
}
declare module 'vuetify/src/components/VFooter/VFooter.js' {
  declare module.exports: $Exports<'vuetify/src/components/VFooter/VFooter'>;
}
declare module 'vuetify/src/components/VForm/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VForm/index'>;
}
declare module 'vuetify/src/components/VForm/VForm.js' {
  declare module.exports: $Exports<'vuetify/src/components/VForm/VForm'>;
}
declare module 'vuetify/src/components/VGrid/grid.js' {
  declare module.exports: $Exports<'vuetify/src/components/VGrid/grid'>;
}
declare module 'vuetify/src/components/VGrid/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VGrid/index'>;
}
declare module 'vuetify/src/components/VGrid/VContainer.js' {
  declare module.exports: $Exports<'vuetify/src/components/VGrid/VContainer'>;
}
declare module 'vuetify/src/components/VGrid/VContent.js' {
  declare module.exports: $Exports<'vuetify/src/components/VGrid/VContent'>;
}
declare module 'vuetify/src/components/VGrid/VFlex.js' {
  declare module.exports: $Exports<'vuetify/src/components/VGrid/VFlex'>;
}
declare module 'vuetify/src/components/VGrid/VLayout.js' {
  declare module.exports: $Exports<'vuetify/src/components/VGrid/VLayout'>;
}
declare module 'vuetify/src/components/VIcon/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VIcon/index'>;
}
declare module 'vuetify/src/components/VIcon/VIcon.js' {
  declare module.exports: $Exports<'vuetify/src/components/VIcon/VIcon'>;
}
declare module 'vuetify/src/components/VJumbotron/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VJumbotron/index'>;
}
declare module 'vuetify/src/components/VJumbotron/VJumbotron.js' {
  declare module.exports: $Exports<'vuetify/src/components/VJumbotron/VJumbotron'>;
}
declare module 'vuetify/src/components/VList/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VList/index'>;
}
declare module 'vuetify/src/components/VList/VList.js' {
  declare module.exports: $Exports<'vuetify/src/components/VList/VList'>;
}
declare module 'vuetify/src/components/VList/VListGroup.js' {
  declare module.exports: $Exports<'vuetify/src/components/VList/VListGroup'>;
}
declare module 'vuetify/src/components/VList/VListTile.js' {
  declare module.exports: $Exports<'vuetify/src/components/VList/VListTile'>;
}
declare module 'vuetify/src/components/VList/VListTileAction.js' {
  declare module.exports: $Exports<'vuetify/src/components/VList/VListTileAction'>;
}
declare module 'vuetify/src/components/VList/VListTileAvatar.js' {
  declare module.exports: $Exports<'vuetify/src/components/VList/VListTileAvatar'>;
}
declare module 'vuetify/src/components/VMenu/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VMenu/index'>;
}
declare module 'vuetify/src/components/VMenu/mixins/menu-activator.js' {
  declare module.exports: $Exports<'vuetify/src/components/VMenu/mixins/menu-activator'>;
}
declare module 'vuetify/src/components/VMenu/mixins/menu-generators.js' {
  declare module.exports: $Exports<'vuetify/src/components/VMenu/mixins/menu-generators'>;
}
declare module 'vuetify/src/components/VMenu/mixins/menu-keyable.js' {
  declare module.exports: $Exports<'vuetify/src/components/VMenu/mixins/menu-keyable'>;
}
declare module 'vuetify/src/components/VMenu/mixins/menu-position.js' {
  declare module.exports: $Exports<'vuetify/src/components/VMenu/mixins/menu-position'>;
}
declare module 'vuetify/src/components/VMenu/VMenu.js' {
  declare module.exports: $Exports<'vuetify/src/components/VMenu/VMenu'>;
}
declare module 'vuetify/src/components/VNavigationDrawer/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VNavigationDrawer/index'>;
}
declare module 'vuetify/src/components/VNavigationDrawer/VNavigationDrawer.js' {
  declare module.exports: $Exports<'vuetify/src/components/VNavigationDrawer/VNavigationDrawer'>;
}
declare module 'vuetify/src/components/VPagination/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VPagination/index'>;
}
declare module 'vuetify/src/components/VPagination/VPagination.js' {
  declare module.exports: $Exports<'vuetify/src/components/VPagination/VPagination'>;
}
declare module 'vuetify/src/components/VParallax/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VParallax/index'>;
}
declare module 'vuetify/src/components/VParallax/VParallax.js' {
  declare module.exports: $Exports<'vuetify/src/components/VParallax/VParallax'>;
}
declare module 'vuetify/src/components/VPicker/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VPicker/index'>;
}
declare module 'vuetify/src/components/VPicker/VPicker.js' {
  declare module.exports: $Exports<'vuetify/src/components/VPicker/VPicker'>;
}
declare module 'vuetify/src/components/VProgressCircular/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VProgressCircular/index'>;
}
declare module 'vuetify/src/components/VProgressCircular/VProgressCircular.js' {
  declare module.exports: $Exports<'vuetify/src/components/VProgressCircular/VProgressCircular'>;
}
declare module 'vuetify/src/components/VProgressLinear/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VProgressLinear/index'>;
}
declare module 'vuetify/src/components/VProgressLinear/VProgressLinear.js' {
  declare module.exports: $Exports<'vuetify/src/components/VProgressLinear/VProgressLinear'>;
}
declare module 'vuetify/src/components/VRadioGroup/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VRadioGroup/index'>;
}
declare module 'vuetify/src/components/VRadioGroup/VRadio.js' {
  declare module.exports: $Exports<'vuetify/src/components/VRadioGroup/VRadio'>;
}
declare module 'vuetify/src/components/VRadioGroup/VRadioGroup.js' {
  declare module.exports: $Exports<'vuetify/src/components/VRadioGroup/VRadioGroup'>;
}
declare module 'vuetify/src/components/VSelect/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/index'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-autocomplete.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-autocomplete'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-computed.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-computed'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-events.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-events'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-generators.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-generators'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-helpers.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-helpers'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-menu.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-menu'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-props.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-props'>;
}
declare module 'vuetify/src/components/VSelect/mixins/select-watchers.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/mixins/select-watchers'>;
}
declare module 'vuetify/src/components/VSelect/VSelect.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSelect/VSelect'>;
}
declare module 'vuetify/src/components/VSlider/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSlider/index'>;
}
declare module 'vuetify/src/components/VSlider/VSlider.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSlider/VSlider'>;
}
declare module 'vuetify/src/components/VSnackbar/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSnackbar/index'>;
}
declare module 'vuetify/src/components/VSnackbar/VSnackbar.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSnackbar/VSnackbar'>;
}
declare module 'vuetify/src/components/VSpeedDial/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSpeedDial/index'>;
}
declare module 'vuetify/src/components/VSpeedDial/VSpeedDial.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSpeedDial/VSpeedDial'>;
}
declare module 'vuetify/src/components/VStepper/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VStepper/index'>;
}
declare module 'vuetify/src/components/VStepper/VStepper.js' {
  declare module.exports: $Exports<'vuetify/src/components/VStepper/VStepper'>;
}
declare module 'vuetify/src/components/VStepper/VStepperContent.js' {
  declare module.exports: $Exports<'vuetify/src/components/VStepper/VStepperContent'>;
}
declare module 'vuetify/src/components/VStepper/VStepperStep.js' {
  declare module.exports: $Exports<'vuetify/src/components/VStepper/VStepperStep'>;
}
declare module 'vuetify/src/components/VSubheader/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSubheader/index'>;
}
declare module 'vuetify/src/components/VSubheader/VSubheader.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSubheader/VSubheader'>;
}
declare module 'vuetify/src/components/VSwitch/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSwitch/index'>;
}
declare module 'vuetify/src/components/VSwitch/VSwitch.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSwitch/VSwitch'>;
}
declare module 'vuetify/src/components/VSystemBar/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSystemBar/index'>;
}
declare module 'vuetify/src/components/VSystemBar/VSystemBar.js' {
  declare module.exports: $Exports<'vuetify/src/components/VSystemBar/VSystemBar'>;
}
declare module 'vuetify/src/components/VTabs/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/index'>;
}
declare module 'vuetify/src/components/VTabs/mixins/tabs-computed.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/mixins/tabs-computed'>;
}
declare module 'vuetify/src/components/VTabs/mixins/tabs-generators.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/mixins/tabs-generators'>;
}
declare module 'vuetify/src/components/VTabs/mixins/tabs-props.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/mixins/tabs-props'>;
}
declare module 'vuetify/src/components/VTabs/mixins/tabs-touch.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/mixins/tabs-touch'>;
}
declare module 'vuetify/src/components/VTabs/mixins/tabs-watchers.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/mixins/tabs-watchers'>;
}
declare module 'vuetify/src/components/VTabs/VTab.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/VTab'>;
}
declare module 'vuetify/src/components/VTabs/VTabItem.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/VTabItem'>;
}
declare module 'vuetify/src/components/VTabs/VTabs.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/VTabs'>;
}
declare module 'vuetify/src/components/VTabs/VTabsItems.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/VTabsItems'>;
}
declare module 'vuetify/src/components/VTabs/VTabsSlider.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTabs/VTabsSlider'>;
}
declare module 'vuetify/src/components/VTextField/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTextField/index'>;
}
declare module 'vuetify/src/components/VTextField/VTextField.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTextField/VTextField'>;
}
declare module 'vuetify/src/components/VTimePicker/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTimePicker/index'>;
}
declare module 'vuetify/src/components/VTimePicker/VTimePicker.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTimePicker/VTimePicker'>;
}
declare module 'vuetify/src/components/VTimePicker/VTimePickerClock.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTimePicker/VTimePickerClock'>;
}
declare module 'vuetify/src/components/VTimePicker/VTimePickerTitle.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTimePicker/VTimePickerTitle'>;
}
declare module 'vuetify/src/components/VToolbar/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VToolbar/index'>;
}
declare module 'vuetify/src/components/VToolbar/VToolbar.js' {
  declare module.exports: $Exports<'vuetify/src/components/VToolbar/VToolbar'>;
}
declare module 'vuetify/src/components/VToolbar/VToolbarSideIcon.js' {
  declare module.exports: $Exports<'vuetify/src/components/VToolbar/VToolbarSideIcon'>;
}
declare module 'vuetify/src/components/VTooltip/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTooltip/index'>;
}
declare module 'vuetify/src/components/VTooltip/VTooltip.js' {
  declare module.exports: $Exports<'vuetify/src/components/VTooltip/VTooltip'>;
}
declare module 'vuetify/src/components/Vuetify/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/Vuetify/index'>;
}
declare module 'vuetify/src/components/Vuetify/mixins/application.js' {
  declare module.exports: $Exports<'vuetify/src/components/Vuetify/mixins/application'>;
}
declare module 'vuetify/src/components/Vuetify/mixins/options.js' {
  declare module.exports: $Exports<'vuetify/src/components/Vuetify/mixins/options'>;
}
declare module 'vuetify/src/components/Vuetify/mixins/theme.js' {
  declare module.exports: $Exports<'vuetify/src/components/Vuetify/mixins/theme'>;
}
declare module 'vuetify/src/components/Vuetify/util/goTo.js' {
  declare module.exports: $Exports<'vuetify/src/components/Vuetify/util/goTo'>;
}
declare module 'vuetify/src/directives/click-outside.js' {
  declare module.exports: $Exports<'vuetify/src/directives/click-outside'>;
}
declare module 'vuetify/src/directives/index.js' {
  declare module.exports: $Exports<'vuetify/src/directives/index'>;
}
declare module 'vuetify/src/directives/resize.js' {
  declare module.exports: $Exports<'vuetify/src/directives/resize'>;
}
declare module 'vuetify/src/directives/ripple.js' {
  declare module.exports: $Exports<'vuetify/src/directives/ripple'>;
}
declare module 'vuetify/src/directives/scroll.js' {
  declare module.exports: $Exports<'vuetify/src/directives/scroll'>;
}
declare module 'vuetify/src/directives/touch.js' {
  declare module.exports: $Exports<'vuetify/src/directives/touch'>;
}
declare module 'vuetify/src/index.js' {
  declare module.exports: $Exports<'vuetify/src/index'>;
}
declare module 'vuetify/src/mixins/applicationable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/applicationable'>;
}
declare module 'vuetify/src/mixins/bootable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/bootable'>;
}
declare module 'vuetify/src/mixins/button-group.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/button-group'>;
}
declare module 'vuetify/src/mixins/colorable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/colorable'>;
}
declare module 'vuetify/src/mixins/data-iterable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/data-iterable'>;
}
declare module 'vuetify/src/mixins/delayable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/delayable'>;
}
declare module 'vuetify/src/mixins/dependent.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/dependent'>;
}
declare module 'vuetify/src/mixins/detachable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/detachable'>;
}
declare module 'vuetify/src/mixins/filterable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/filterable'>;
}
declare module 'vuetify/src/mixins/input.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/input'>;
}
declare module 'vuetify/src/mixins/loadable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/loadable'>;
}
declare module 'vuetify/src/mixins/maskable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/maskable'>;
}
declare module 'vuetify/src/mixins/menuable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/menuable'>;
}
declare module 'vuetify/src/mixins/overlayable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/overlayable'>;
}
declare module 'vuetify/src/mixins/picker-button.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/picker-button'>;
}
declare module 'vuetify/src/mixins/picker.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/picker'>;
}
declare module 'vuetify/src/mixins/positionable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/positionable'>;
}
declare module 'vuetify/src/mixins/registrable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/registrable'>;
}
declare module 'vuetify/src/mixins/returnable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/returnable'>;
}
declare module 'vuetify/src/mixins/rippleable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/rippleable'>;
}
declare module 'vuetify/src/mixins/routable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/routable'>;
}
declare module 'vuetify/src/mixins/selectable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/selectable'>;
}
declare module 'vuetify/src/mixins/soloable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/soloable'>;
}
declare module 'vuetify/src/mixins/ssr-bootable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/ssr-bootable'>;
}
declare module 'vuetify/src/mixins/stackable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/stackable'>;
}
declare module 'vuetify/src/mixins/tab-focusable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/tab-focusable'>;
}
declare module 'vuetify/src/mixins/themeable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/themeable'>;
}
declare module 'vuetify/src/mixins/toggleable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/toggleable'>;
}
declare module 'vuetify/src/mixins/transitionable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/transitionable'>;
}
declare module 'vuetify/src/mixins/translatable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/translatable'>;
}
declare module 'vuetify/src/mixins/validatable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/validatable'>;
}
declare module 'vuetify/src/util/color/transformCIELAB.js' {
  declare module.exports: $Exports<'vuetify/src/util/color/transformCIELAB'>;
}
declare module 'vuetify/src/util/color/transformSRGB.js' {
  declare module.exports: $Exports<'vuetify/src/util/color/transformSRGB'>;
}
declare module 'vuetify/src/util/colors.js' {
  declare module.exports: $Exports<'vuetify/src/util/colors'>;
}
declare module 'vuetify/src/util/colorUtils.js' {
  declare module.exports: $Exports<'vuetify/src/util/colorUtils'>;
}
declare module 'vuetify/src/util/console.js' {
  declare module.exports: $Exports<'vuetify/src/util/console'>;
}
declare module 'vuetify/src/util/easing-patterns.js' {
  declare module.exports: $Exports<'vuetify/src/util/easing-patterns'>;
}
declare module 'vuetify/src/util/helpers.js' {
  declare module.exports: $Exports<'vuetify/src/util/helpers'>;
}
declare module 'vuetify/src/util/mask.js' {
  declare module.exports: $Exports<'vuetify/src/util/mask'>;
}
declare module 'vuetify/src/util/theme.js' {
  declare module.exports: $Exports<'vuetify/src/util/theme'>;
}
declare module 'vuetify/test/index.js' {
  declare module.exports: $Exports<'vuetify/test/index'>;
}
declare module 'vuetify/test/util/to-have-been-warned.js' {
  declare module.exports: $Exports<'vuetify/test/util/to-have-been-warned'>;
}
