// flow-typed signature: fa90af33dd169c7b2da51d287aada70f
// flow-typed version: <<STUB>>/vuex-i18n_v^1.10.5/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuex-i18n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuex-i18n' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuex-i18n/dist/vuex-i18n.cjs' {
  declare module.exports: any;
}

declare module 'vuex-i18n/dist/vuex-i18n.es' {
  declare module.exports: any;
}

declare module 'vuex-i18n/dist/vuex-i18n.min' {
  declare module.exports: any;
}

declare module 'vuex-i18n/dist/vuex-i18n.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuex-i18n/dist/vuex-i18n.cjs.js' {
  declare module.exports: $Exports<'vuex-i18n/dist/vuex-i18n.cjs'>;
}
declare module 'vuex-i18n/dist/vuex-i18n.es.js' {
  declare module.exports: $Exports<'vuex-i18n/dist/vuex-i18n.es'>;
}
declare module 'vuex-i18n/dist/vuex-i18n.min.js' {
  declare module.exports: $Exports<'vuex-i18n/dist/vuex-i18n.min'>;
}
declare module 'vuex-i18n/dist/vuex-i18n.umd.js' {
  declare module.exports: $Exports<'vuex-i18n/dist/vuex-i18n.umd'>;
}
